[client]
port=3308

[mysqld]
port=3308
bind-address=127.0.0.1

basedir=D:/wampp64/www/urea/runtime/mysql
datadir=D:/wampp64/www/urea/runtime/mysql-data

character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

default_storage_engine=InnoDB

mysqlx=0
skip_name_resolve

max_allowed_packet=64M

innodb_buffer_pool_size=256M
innodb_file_per_table=1
innodb_flush_log_at_trx_commit=1

log_error=D:/wampp64/www/urea/runtime/mysql-data/mysql-error.log

sql_mode=""

skip_log_bin